version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - stack.env
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - rabbitmq_network
    restart: always

  rabbitmq2:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
    env_file:
      - stack.env
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      JOIN_CLUSTER_HOST: rabbitmq1
    networks:
      - rabbitmq_network
    restart: always
    depends_on:
      - rabbitmq1
    volumes:
      - ${RABBITMQ_PATH}/join-cluster.sh:/usr/local/bin/join-cluster.sh
    entrypoint: /usr/local/bin/join-cluster.sh

  rabbitmq3:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5674:5672"
    env_file:
      - stack.env
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      JOIN_CLUSTER_HOST: rabbitmq1
    networks:
      - rabbitmq_network
    restart: always
    depends_on:
      - rabbitmq1
    volumes:
      - ${RABBITMQ_PATH}/join-cluster.sh:/usr/local/bin/join-cluster.sh
    entrypoint: /usr/local/bin/join-cluster.sh


networks:
  rabbitmq_network:
    driver: bridge
